log_dir: "/micklem/data/pombemine/download-logs"
data_dir: "/micklem/data/pombemine"

# commented out datasource used by PombeMine which are not update automatically
default_sources:
  - "PombeGene"
  - "PombeGoAnnotation"
  - "PombeOrthologs"
  - "PombePhenotype"
  - "PombeFasta"
  - "Mondo"
  - "MondoOntology"
  - "EcoAnnotation"
  - "Fypo"
  - "BasicGoAnnotation"
#  - "BioGRID"
#  - "IntActVocabulary"
#  - "InterPro"
#  - "InterProGO"
#  - "InterProProtein"
  - "NCBIGene"
#  - "OMIM"
#  - "Panther"
#  - "UniProt"

UniProt:
    organisms:
        - 284812
    excluded_organisms:
        - 9606
        - 10091
        - 10092
        - 35531
        - 39442
        - 46244
        - 57486
        - 63221
        - 116058
        - 1643390
        - 180454
        - 377270
        - 377271
        - 377586
        - 377587
        - 741158
        - 943925
        - 943926
        - 3702
        - 6239
        - 7165
        - 7217
        - 7220
        - 7222
        - 7227
        - 7230
        - 7234
        - 7238
        - 7240
        - 7244
        - 7245
        - 7260
        - 7955
        - 10090
        - 10116
        - 46245
        - 559292
        - 6238
        - 31234
        - 135651
        - 281687
