log_dir: "/micklem/data/pombemine/download-logs"
data_dir: "/micklem/data/pombemine"

default_sources:
  - "PombeGene"
  - "PombeGoAnnotation"
  - "PombeHumanOrthologs"
  - "PombeCerevisiaeOrthologs"
  - "PombePhenotype"
  - "PombeFasta"
  - "Mondo"
  - "MondoOntology"
  - "FypoExtension"
  - "Fypo"
